-- begin BACKMON_BACKUP_TARGET
alter table BACKMON_BACKUP_TARGET add constraint FK_BACKMON_BACKUP_TARGET_ON_BACKUP_SPHERE foreign key (BACKUP_SPHERE_ID) references BACKMON_BACKUP_SPHERE(ID)^
alter table BACKMON_BACKUP_TARGET add constraint FK_BACKMON_BACKUP_TARGET_ON_FILE_DATA_FETCHER foreign key (FILE_DATA_FETCHER_ID) references BACKMON_FILE_DATA_FETCHER(ID)^
create index IDX_BACKMON_BACKUP_TARGET_ON_BACKUP_SPHERE on BACKMON_BACKUP_TARGET (BACKUP_SPHERE_ID)^
create index IDX_BACKMON_BACKUP_TARGET_ON_FILE_DATA_FETCHER on BACKMON_BACKUP_TARGET (FILE_DATA_FETCHER_ID)^
-- end BACKMON_BACKUP_TARGET
-- begin BACKMON_BACKUP_FOLDER
alter table BACKMON_BACKUP_FOLDER add constraint FK_BACKMON_BACKUP_FOLDER_ON_BACKUP_TARGET foreign key (BACKUP_TARGET_ID) references BACKMON_BACKUP_TARGET(ID)^
create index IDX_BACKMON_BACKUP_FOLDER_ON_BACKUP_TARGET on BACKMON_BACKUP_FOLDER (BACKUP_TARGET_ID)^
-- end BACKMON_BACKUP_FOLDER
-- begin BACKMON_NOTIFICATION_RECEIVER
alter table BACKMON_NOTIFICATION_RECEIVER add constraint FK_BACKMON_NOTIFICATION_RECEIVER_ON_BACKUP_SPHERE foreign key (BACKUP_SPHERE_ID) references BACKMON_BACKUP_SPHERE(ID)^
create index IDX_BACKMON_NOTIFICATION_RECEIVER_ON_BACKUP_SPHERE on BACKMON_NOTIFICATION_RECEIVER (BACKUP_SPHERE_ID)^
-- end BACKMON_NOTIFICATION_RECEIVER
-- begin BACKMON_BACKUP_CHECK
alter table BACKMON_BACKUP_CHECK add constraint FK_BACKMON_BACKUP_CHECK_ON_COMPARE_ORIGIN foreign key (COMPARE_ORIGIN_ID) references BACKMON_BACKUP_TARGET(ID)^
alter table BACKMON_BACKUP_CHECK add constraint FK_BACKMON_BACKUP_CHECK_ON_COMPARE_TARGET foreign key (COMPARE_TARGET_ID) references BACKMON_BACKUP_TARGET(ID)^
create index IDX_BACKMON_BACKUP_CHECK_ON_COMPARE_ORIGIN on BACKMON_BACKUP_CHECK (COMPARE_ORIGIN_ID)^
create index IDX_BACKMON_BACKUP_CHECK_ON_COMPARE_TARGET on BACKMON_BACKUP_CHECK (COMPARE_TARGET_ID)^
-- end BACKMON_BACKUP_CHECK
-- begin BACKMON_BACKUP_FILE
alter table BACKMON_BACKUP_FILE add constraint FK_BACKMON_BACKUP_FILE_ON_BACKUP_FOLDER foreign key (BACKUP_FOLDER_ID) references BACKMON_BACKUP_FOLDER(ID)^
create index IDX_BACKMON_BACKUP_FILE_ON_BACKUP_FOLDER on BACKMON_BACKUP_FILE (BACKUP_FOLDER_ID)^
-- end BACKMON_BACKUP_FILE
